/**
 * AI Service Revenue – tracks revenue generated by AI service usage:
 * prompt generation, video rendering, analytics queries, API calls.
 *
 * Billing model: per-call, per-token, per-second, or subscription add-on.
 */
export function createAiServiceRevenue(deps = {}) {
  const usageLog = []; // { serviceId, customerId, units, unitPrice, amount, billType, ts }
  const tariffs  = new Map(); // serviceId -> { unitPrice, billType }

  function registerService({ serviceId, unitPrice, billType = 'per_call' }) {
    tariffs.set(serviceId, { serviceId, unitPrice, billType });
  }

  function recordUsage({ serviceId, customerId, units = 1, ts = null }) {
    const tariff = tariffs.get(serviceId) || { unitPrice: 0, billType: 'per_call' };
    const amount = units * tariff.unitPrice;
    const entry  = { serviceId, customerId, units, unitPrice: tariff.unitPrice, amount, billType: tariff.billType, ts: ts || new Date().toISOString() };
    usageLog.push(entry);
    return entry;
  }

  function revenue(filter = {}) {
    let data = usageLog;
    if (filter.serviceId)  data = data.filter((e) => e.serviceId  === filter.serviceId);
    if (filter.customerId) data = data.filter((e) => e.customerId === filter.customerId);
    if (filter.since)      data = data.filter((e) => e.ts >= filter.since);
    const totalAmount = data.reduce((s, e) => s + e.amount, 0);
    const totalUnits  = data.reduce((s, e) => s + e.units, 0);
    return { totalAmount, totalUnits, entryCount: data.length };
  }

  function byService() {
    const services = [...new Set(usageLog.map((e) => e.serviceId))];
    return services.map((id) => ({ serviceId: id, ...revenue({ serviceId: id }) }));
  }

  function topCustomers(limit = 5) {
    const agg = {};
    for (const e of usageLog) agg[e.customerId] = (agg[e.customerId] || 0) + e.amount;
    return Object.entries(agg).sort((a, b) => b[1] - a[1]).slice(0, limit).map(([customerId, amount]) => ({ customerId, amount }));
  }

  return { registerService, recordUsage, revenue, byService, topCustomers };
}

export default createAiServiceRevenue;
