{{- if .Values.security.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aqond.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "aqond.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
