global:
  env: dev
  imageTag: dev
  namespace: aqond-dev

ingress:
  host: aqond-dev.local

autoscaling:
  hpa:
    minReplicas: 1
    maxReplicas: 5
  keda:
    orderMinReplicas: 1
    orderMaxReplicas: 8

mesh:
  enabled: false

progressiveDelivery:
  enabled: false

citus:
  enabled: false
