-- 033: Fix missing columns (u.name, deposit_amount, completed_jobs_count, etc.)
ALTER TABLE users ADD COLUMN IF NOT EXISTS name VARCHAR(255);
UPDATE users SET name = full_name WHERE name IS NULL AND full_name IS NOT NULL;
ALTER TABLE users ADD COLUMN IF NOT EXISTS completed_jobs_count INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS rating DECIMAL(3,2) DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS account_status VARCHAR(50) DEFAULT 'active';
ALTER TABLE users ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS expert_category VARCHAR(100);
ALTER TABLE users ADD COLUMN IF NOT EXISTS portfolio_urls JSONB;
ALTER TABLE users ADD COLUMN IF NOT EXISTS greeting_video_url TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS verified_badge BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS signature_service TEXT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS the_journey TEXT;
ALTER TABLE kyc_documents ADD COLUMN IF NOT EXISTS user_id UUID REFERENCES users(id);
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS deposit_amount NUMERIC(12,2) DEFAULT 0;
ALTER TABLE bookings ADD COLUMN IF NOT EXISTS deposit_status VARCHAR(20) DEFAULT 'none';
