apiVersion: v1
kind: Service
metadata:
  name: aqond-redis
  namespace: aqond-dev
spec:
  ports:
    - port: 6379
  selector:
    app: aqond-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aqond-redis
  namespace: aqond-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aqond-redis
  template:
    metadata:
      labels:
        app: aqond-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
