apiVersion: v1
kind: Service
metadata:
  name: scylla
  namespace: aqond-dev
spec:
  ports:
    - port: 9042
  selector:
    app: scylla
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: scylla
  namespace: aqond-dev
spec:
  serviceName: scylla
  replicas: 1
  selector:
    matchLabels:
      app: scylla
  template:
    metadata:
      labels:
        app: scylla
    spec:
      containers:
        - name: scylla
          image: scylladb/scylla:5.4
          args: ["--smp", "1", "--memory", "750M", "--overprovisioned", "1"]
          ports:
            - containerPort: 9042
