// pages/Payment.tsx - Updated for Phase 3 Payment Gateway Integration
import React, { useEffect, useState } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { BackendPaymentService } from "../services/backendPaymentService";
import paymentGatewayService, {
  PaymentGateway,
  PaymentStatus as GatewayPaymentStatus,
  PAYMENT_FEE,
} from "../services/paymentGatewayService";
import { MockApi } from "../services/mockApi";
import {
  recordPaymentCreated,
  recordPaymentCompleted,
} from "../services/ledgerService";
import { Job, PaymentMethod } from "../types";
import { useLanguage } from "../context/LanguageContext";
import { useAuth } from "../context/AuthContext";
import { useNotification } from "../context/NotificationContext";
import {
  CreditCard,
  QrCode,
  Wallet,
  CheckCircle,
  Loader2,
  AlertCircle,
  User,
  Calendar,
  Lock,
  Tag,
  Receipt,
  Shield,
  Clock,
} from "lucide-react";

export const Payment: React.FC = () => {
  const { jobId } = useParams<{ jobId: string }>();
  const navigate = useNavigate();
  const { t } = useLanguage();
  const { user, login, token } = useAuth();
  const { notify } = useNotification();

  const [job, setJob] = useState<Job | null>(null);
  const [loading, setLoading] = useState(true);
  const [processing, setProcessing] = useState(false);
  const [method, setMethod] = useState<PaymentMethod>(PaymentMethod.PROMPTPAY);
  const [success, setSuccess] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [qrCodeUrl, setQrCodeUrl] = useState<string | null>(null);

  // Voucher State
  const [voucherCode, setVoucherCode] = useState("");
  const [discount, setDiscount] = useState(0);
  const [voucherApplied, setVoucherApplied] = useState(false);

  // Payment Status
  const [paymentStatus, setPaymentStatus] = useState<any>(null);
  const [transactionId, setTransactionId] = useState<string>("");
  const [showReceipt, setShowReceipt] = useState(false);
  const [receiptUrl, setReceiptUrl] = useState<string>("");
  const [autotestMode, setAutotestMode] = useState(false);

  useEffect(() => {
    const loadJobAndPaymentStatus = async () => {
      if (!jobId) return;

      try {
        // 1. โหลดข้อมูลงาน
        const jobData = await MockApi.getJobDetails(jobId);
        setJob(jobData || null);

        // 2. ตรวจสอบสถานะการชำระเงินจาก Backend
        if (jobData) {
          const status = await BackendPaymentService.getPaymentStatus(jobId);
          setPaymentStatus(status);

          // ถ้าชำระเงินสำเร็จแล้ว
          if (status.status === "completed") {
            setSuccess(true);
            setTransactionId(status.transactionId);

            // โหลดใบเสร็จ
            try {
              const receipt =
                await BackendPaymentService.generateReceipt(jobId);
              setReceiptUrl(receipt);
            } catch (error) {
              console.warn("Could not load receipt:", error);
            }
          }
        }
      } catch (error) {
        console.error("Failed to load payment data:", error);
        notify(t("common.error_loading"), "error");
      } finally {
        setLoading(false);
      }
    };

    loadJobAndPaymentStatus();
  }, [jobId, notify, t]);

  // Remove old QR generation - will be generated by gateway service when payment is created

  const handleApplyVoucher = async () => {
    if (!voucherCode) return;
    try {
      // TODO: สร้าง voucher service ใน backend
      const v = await MockApi.validateVoucher(voucherCode);
      if (job && job.price >= v.min_spend) {
        setDiscount(v.discount_amount);
        setVoucherApplied(true);
        notify("Voucher applied successfully!", "success");
      } else {
        notify(`Minimum spend is ${v.min_spend}`, "error");
      }
    } catch (err) {
      notify("Invalid Voucher Code", "error");
    }
  };

  const handlePayment = async () => {
    if (!job || !user) return;

    setProcessing(true);
    setError(null);
    setQrCodeUrl(null);

    try {
      const finalPrice = Math.max(0, job.price - discount);

      // Map PaymentMethod to PaymentGateway (PromptPay = 3-5 THB fee; Card = 19 THB)
      let gateway: PaymentGateway;
      if (method === PaymentMethod.PROMPTPAY) {
        gateway = PaymentGateway.PROMPTPAY;
      } else if (method === PaymentMethod.CREDIT_CARD) {
        gateway = PaymentGateway.STRIPE;
      } else {
        gateway = PaymentGateway.PROMPTPAY;
      }

      let paymentResult: Awaited<
        ReturnType<typeof paymentGatewayService.createPayment>
      >;

      if (autotestMode && gateway === PaymentGateway.PROMPTPAY) {
        paymentResult = paymentGatewayService.createPromptPayPaymentTest(
          finalPrice,
          job.id,
          { user_id: user.id, job_title: job.title },
        );
      } else {
        paymentResult = await paymentGatewayService.createPayment({
          job_id: job.id,
          amount: finalPrice,
          gateway: gateway,
          metadata: {
            user_id: user.id,
            user_name: user.name || user.email,
            job_title: job.title,
            job_category: job.category,
          },
        });
      }

      if (!paymentResult.success) {
        throw new Error(paymentResult.error || "Payment creation failed");
      }

      // Phase 3: Append to immutable ledger (payment_created)
      const ledgerGateway =
        gateway === PaymentGateway.PROMPTPAY
          ? "promptpay"
          : gateway === PaymentGateway.STRIPE
            ? "stripe"
            : "truemoney";
      try {
        await recordPaymentCreated({
          payment_id: paymentResult.payment_id,
          gateway: ledgerGateway,
          job_id: job.id,
          amount: finalPrice,
          currency: paymentResult.currency || "THB",
          bill_no: paymentResult.bill_no,
          transaction_no: paymentResult.transaction_no,
          user_id: user.id,
          metadata: { job_title: job.title },
        });
      } catch (ledgerErr) {
        console.warn(
          "Ledger recordPaymentCreated failed (non-blocking):",
          ledgerErr,
        );
      }

      setTransactionId(paymentResult.transaction_no);

      // 2. Handle based on gateway type
      if (gateway !== PaymentGateway.STRIPE) {
        // Display QR code from gateway
        if (paymentResult.qr_code_url) {
          setQrCodeUrl(paymentResult.qr_code_url);
        }

        notify("QR Code generated! Please scan to pay", "info");

        // 3. Poll payment status (autotest: simulate completed after 2.5s)
        try {
          let status: GatewayPaymentStatus;
          if (autotestMode && paymentResult.payment_id.startsWith("pp_test_")) {
            await new Promise((r) => setTimeout(r, 2500));
            status = paymentGatewayService.checkPaymentStatusTest(
              paymentResult.payment_id,
            );
          } else {
            status = await paymentGatewayService.pollPaymentStatus(
              paymentResult.payment_id,
              gateway,
              60,
              5000,
            );
          }

          if (status === GatewayPaymentStatus.COMPLETED) {
            // Phase 3: Append to immutable ledger (payment_completed)
            try {
              await recordPaymentCompleted({
                payment_id: paymentResult.payment_id,
                gateway: ledgerGateway,
                job_id: job.id,
                amount: finalPrice,
                currency: paymentResult.currency || "THB",
                bill_no: paymentResult.bill_no,
                transaction_no: paymentResult.transaction_no,
                user_id: user.id,
                provider_id: job.accepted_by || undefined,
                metadata: { job_title: job.title },
              });
            } catch (ledgerErr) {
              console.warn(
                "Ledger recordPaymentCompleted failed (non-blocking):",
                ledgerErr,
              );
            }
            // Payment successful
            setSuccess(true);
            notify(t("payment.success_title"), "success");

            // Generate receipt
            const receipt = await BackendPaymentService.generateReceipt(job.id);
            setReceiptUrl(receipt);
          } else {
            throw new Error(`Payment ${status}`);
          }
        } catch (pollError: any) {
          throw new Error(pollError.message || "Payment verification timeout");
        }
      } else if (gateway === PaymentGateway.STRIPE) {
        // For Stripe, we need to use Stripe Elements
        // This will be handled by Stripe's frontend SDK
        notify("Please complete card payment", "info");
        // TODO: Integrate @stripe/react-stripe-js for card input
      }

      // 4. Update user wallet balance (if wallet payment)
      if (method === PaymentMethod.WALLET && user) {
        const updatedUser = {
          ...user,
          wallet_balance: (user.wallet_balance || 0) - finalPrice,
        };
        login(updatedUser, token || "");
      }
    } catch (error: any) {
      console.error("Payment processing failed:", error);

      const errorMessage =
        error.response?.data?.error ||
        error.message ||
        "Payment failed. Please try again.";

      setError(errorMessage);
      notify("Payment failed", "error");
    } finally {
      setProcessing(false);
    }
  };

  const handleViewReceipt = async () => {
    if (!jobId) return;

    try {
      if (!receiptUrl) {
        const receipt = await BackendPaymentService.generateReceipt(jobId);
        setReceiptUrl(receipt);
      }
      setShowReceipt(true);
    } catch (error) {
      notify("Failed to load receipt", "error");
    }
  };

  const handleDownloadReceipt = () => {
    if (receiptUrl) {
      const link = document.createElement("a");
      link.href = receiptUrl;
      link.download = `receipt-${transactionId}.pdf`;
      link.click();
    }
  };

  if (loading) {
    return (
      <div className="min-h-[60vh] flex flex-col items-center justify-center">
        <div className="w-16 h-16 border-4 border-emerald-200 border-t-emerald-600 rounded-full animate-spin mb-4"></div>
        <p className="text-gray-500">{t("common.loading")}</p>
      </div>
    );
  }

  if (!job) {
    return (
      <div className="min-h-[60vh] flex flex-col items-center justify-center text-center px-4">
        <AlertCircle className="w-16 h-16 text-red-400 mb-4" />
        <h2 className="text-xl font-bold text-gray-900 mb-2">
          {t("detail.not_found")}
        </h2>
        <button
          onClick={() => navigate("/")}
          className="mt-4 px-6 py-2 bg-emerald-600 text-white rounded-lg hover:bg-emerald-700 transition-colors"
        >
          {t("common.back_home")}
        </button>
      </div>
    );
  }

  if (success) {
    return (
      <div className="min-h-[60vh] flex flex-col items-center justify-center text-center px-4 max-w-md mx-auto">
        <div className="w-24 h-24 bg-gradient-to-br from-emerald-100 to-green-100 rounded-full flex items-center justify-center mb-6 animate-bounce">
          <CheckCircle size={48} className="text-emerald-600" />
        </div>

        <div className="mb-2">
          <h2 className="text-2xl font-bold text-gray-900">
            {t("payment.success_title")}
          </h2>
          <p className="text-gray-500 mt-2">{t("payment.success_desc")}</p>
        </div>

        <div className="bg-gradient-to-br from-gray-50 to-white rounded-2xl p-6 w-full mb-8 border border-gray-100 shadow-sm">
          <div className="grid grid-cols-2 gap-4 mb-4">
            <div className="text-left">
              <p className="text-xs text-gray-500 uppercase tracking-wider font-medium mb-1">
                Amount Paid
              </p>
              <p className="font-bold text-gray-900 text-lg">
                {Math.max(0, job.price - discount)} THB
              </p>
            </div>
            <div className="text-right">
              <p className="text-xs text-gray-500 uppercase tracking-wider font-medium mb-1">
                Method
              </p>
              <p className="font-medium text-gray-900 uppercase text-sm">
                {method.replace("_", " ")}
              </p>
            </div>
          </div>

          <div className="border-t border-gray-100 pt-4">
            <p className="text-xs text-gray-500 uppercase tracking-wider font-medium mb-1">
              Transaction ID
            </p>
            <p className="font-mono text-sm text-gray-700 bg-gray-50 px-3 py-2 rounded-lg">
              {transactionId || `TX-${Date.now().toString().slice(-8)}`}
            </p>
          </div>

          {receiptUrl && (
            <div className="mt-4 flex gap-2">
              <button
                onClick={handleViewReceipt}
                className="flex-1 px-4 py-2 bg-emerald-50 text-emerald-700 rounded-lg font-medium hover:bg-emerald-100 transition-colors flex items-center justify-center"
              >
                <Receipt size={18} className="mr-2" />
                View Receipt
              </button>
              <button
                onClick={handleDownloadReceipt}
                className="flex-1 px-4 py-2 bg-white text-gray-700 rounded-lg font-medium hover:bg-gray-50 transition-colors border border-gray-200 flex items-center justify-center"
              >
                Download
              </button>
            </div>
          )}
        </div>

        <div className="flex gap-3 w-full">
          <button
            onClick={() => navigate(`/job/${jobId}`)}
            className="flex-1 px-6 py-3 bg-gray-100 text-gray-700 rounded-lg font-bold hover:bg-gray-200 transition-colors"
          >
            View Job Details
          </button>
          <button
            onClick={() => navigate("/my-jobs")}
            className="flex-1 px-6 py-3 bg-emerald-600 text-white rounded-lg font-bold hover:bg-emerald-700 transition-colors"
          >
            {t("payment.view_my_jobs")}
          </button>
        </div>

        {showReceipt && receiptUrl && (
          <div className="fixed inset-0 bg-black/50 flex items-center justify-center p-4 z-50">
            <div className="bg-white rounded-2xl max-w-2xl w-full max-h-[90vh] overflow-hidden">
              <div className="p-4 border-b border-gray-200 flex justify-between items-center">
                <h3 className="font-bold text-gray-900">Payment Receipt</h3>
                <button
                  onClick={() => setShowReceipt(false)}
                  className="text-gray-500 hover:text-gray-700"
                >
                  ✕
                </button>
              </div>
              <div className="p-4 overflow-auto">
                <iframe
                  src={receiptUrl}
                  className="w-full h-[70vh] border-0"
                  title="Payment Receipt"
                />
              </div>
            </div>
          </div>
        )}
      </div>
    );
  }

  const finalPrice = Math.max(0, job.price - discount);

  return (
    <div className="max-w-6xl mx-auto px-4 py-8">
      <div className="mb-8">
        <h1 className="text-3xl font-bold text-gray-900 mb-2 flex items-center">
          <Shield className="w-8 h-8 text-emerald-600 mr-3" />
          {t("payment.title")}
        </h1>
        <p className="text-gray-500">Complete your payment securely</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Left Column - Order Summary */}
        <div className="lg:col-span-1">
          <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6 sticky top-24">
            <div className="flex items-center justify-between mb-6">
              <h3 className="font-bold text-gray-900 text-lg">
                {t("payment.order_summary")}
              </h3>
              <span className="text-xs font-medium px-2 py-1 bg-emerald-100 text-emerald-700 rounded-full">
                {job.status}
              </span>
            </div>

            <div className="space-y-4 mb-6">
              <div>
                <h4 className="font-medium text-gray-900 mb-1">{job.title}</h4>
                <p className="text-sm text-gray-500">
                  {job.description?.substring(0, 100)}...
                </p>
              </div>

              <div className="border-t border-gray-100 pt-4 space-y-3">
                <div className="flex justify-between text-sm">
                  <span className="text-gray-600">Base Price</span>
                  <span className="font-medium">{job.price} THB</span>
                </div>
                <div className="flex justify-between text-sm">
                  <span className="text-gray-600">Service Fee</span>
                  <span className="font-medium">0 THB</span>
                </div>
                {discount > 0 && (
                  <div className="flex justify-between text-sm">
                    <span className="text-emerald-600 font-medium">
                      Discount
                    </span>
                    <span className="font-bold text-emerald-600">
                      -{discount} THB
                    </span>
                  </div>
                )}
              </div>

              <div className="border-t border-gray-200 pt-4">
                <div className="flex justify-between items-center">
                  <span className="font-bold text-gray-900">Total Amount</span>
                  <div className="text-right">
                    <div className="text-2xl font-bold text-emerald-600">
                      {finalPrice} THB
                    </div>
                    <div className="text-xs text-gray-500">
                      Inclusive of all taxes
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {/* Voucher Section */}
            <div className="border-t border-gray-100 pt-6">
              <label className="block text-sm font-medium text-gray-900 mb-2 flex items-center">
                <Tag className="w-4 h-4 mr-2" />
                {t("payment.voucher")}
              </label>
              <div className="flex gap-2">
                <input
                  type="text"
                  value={voucherCode}
                  onChange={(e) => setVoucherCode(e.target.value.toUpperCase())}
                  placeholder="ENTER CODE"
                  disabled={voucherApplied}
                  className="flex-1 px-4 py-2.5 border border-gray-300 rounded-lg focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500 transition-all uppercase font-medium disabled:bg-gray-50"
                />
                <button
                  onClick={handleApplyVoucher}
                  disabled={!voucherCode.trim() || voucherApplied}
                  className="px-4 py-2.5 bg-gray-900 text-white font-medium rounded-lg hover:bg-gray-800 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
                >
                  {voucherApplied ? "Applied" : "Apply"}
                </button>
              </div>
              {voucherApplied && (
                <p className="text-sm text-emerald-600 mt-2 flex items-center">
                  <CheckCircle className="w-4 h-4 mr-1" />
                  Discount applied successfully!
                </p>
              )}
            </div>

            {/* Security Badges */}
            <div className="mt-6 pt-6 border-t border-gray-100 grid grid-cols-2 gap-3">
              <div className="text-center p-3 bg-gray-50 rounded-lg">
                <Shield className="w-6 h-6 text-emerald-600 mx-auto mb-1" />
                <p className="text-xs font-medium text-gray-700">
                  Secure Payment
                </p>
              </div>
              <div className="text-center p-3 bg-gray-50 rounded-lg">
                <Lock className="w-6 h-6 text-emerald-600 mx-auto mb-1" />
                <p className="text-xs font-medium text-gray-700">256-bit SSL</p>
              </div>
            </div>
          </div>
        </div>

        {/* Right Column - Payment Method & Processing */}
        <div className="lg:col-span-2">
          <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-6 mb-6">
            <h3 className="font-bold text-gray-900 text-lg mb-6">
              {t("payment.select_method")}
            </h3>

            {/* Payment Method Selection */}
            <p className="text-xs text-gray-500 mb-4">
              PromptPay QR: ~{PAYMENT_FEE.PROMPTPAY_THB} THB fee · Card: ~
              {PAYMENT_FEE.CARD_THB} THB fee
            </p>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-8">
              {Object.values(PaymentMethod).map((pm) => (
                <button
                  key={pm}
                  onClick={() => setMethod(pm)}
                  className={`p-5 rounded-xl border-2 flex flex-col items-center justify-center transition-all duration-300 ${
                    method === pm
                      ? "border-emerald-500 bg-emerald-50 text-emerald-700 shadow-sm"
                      : "border-gray-100 hover:border-emerald-200 hover:bg-gray-50 text-gray-700"
                  }`}
                >
                  {pm === PaymentMethod.PROMPTPAY && (
                    <QrCode className="w-8 h-8 mb-3" />
                  )}
                  {pm === PaymentMethod.CREDIT_CARD && (
                    <CreditCard className="w-8 h-8 mb-3" />
                  )}
                  {pm === PaymentMethod.WALLET && (
                    <Wallet className="w-8 h-8 mb-3" />
                  )}
                  <span className="font-bold text-sm">
                    {pm === PaymentMethod.PROMPTPAY
                      ? t("payment.promptpay")
                      : pm === PaymentMethod.CREDIT_CARD
                        ? t("payment.credit_card")
                        : t("payment.wallet")}
                  </span>
                  {method === pm && (
                    <div className="w-3 h-3 bg-emerald-500 rounded-full mt-3 animate-pulse"></div>
                  )}
                </button>
              ))}
            </div>

            {/* Payment Details Based on Method */}
            <div className="bg-gradient-to-br from-gray-50 to-white rounded-xl p-6 border border-gray-200 mb-6">
              {method === PaymentMethod.PROMPTPAY && (
                <div className="text-center">
                  <div className="inline-flex items-center px-4 py-2 bg-emerald-100 text-emerald-700 rounded-full mb-6">
                    <Clock className="w-4 h-4 mr-2" />
                    <span className="text-sm font-medium">
                      Valid for 15 minutes
                    </span>
                  </div>

                  <div className="flex flex-col items-center">
                    {qrCodeUrl ? (
                      <>
                        <div className="p-4 bg-white rounded-2xl border-2 border-emerald-100 mb-6 shadow-sm">
                          <img
                            src={qrCodeUrl}
                            alt="PromptPay QR Code"
                            className="w-56 h-56"
                          />
                        </div>
                        <p className="text-sm text-gray-600 mb-4">
                          Scan this QR code with any banking app to pay
                        </p>
                      </>
                    ) : (
                      <div className="w-56 h-56 bg-gray-100 rounded-2xl flex items-center justify-center mb-6">
                        <Loader2 className="w-8 h-8 text-gray-400 animate-spin" />
                      </div>
                    )}

                    <div className="bg-gray-900 text-white rounded-xl p-4 w-full max-w-sm">
                      <p className="text-sm opacity-90 mb-1">Amount to Pay</p>
                      <p className="text-3xl font-bold">{finalPrice} THB</p>
                      <p className="text-xs opacity-75 mt-2">
                        Ref: {jobId?.slice(-8).toUpperCase()}
                      </p>
                    </div>
                  </div>
                </div>
              )}

              {method === PaymentMethod.CREDIT_CARD && (
                <div className="max-w-md mx-auto space-y-4">
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      Card Number
                    </label>
                    <div className="relative">
                      <CreditCard className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" />
                      <input
                        type="text"
                        placeholder="1234 5678 9012 3456"
                        className="w-full pl-12 pr-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500 transition-shadow"
                      />
                    </div>
                  </div>

                  <div className="grid grid-cols-2 gap-4">
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-2">
                        Expiry Date
                      </label>
                      <input
                        type="text"
                        placeholder="MM/YY"
                        className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500"
                      />
                    </div>
                    <div>
                      <label className="block text-sm font-medium text-gray-700 mb-2">
                        CVV
                      </label>
                      <div className="relative">
                        <Lock className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" />
                        <input
                          type="text"
                          placeholder="123"
                          className="w-full pl-12 pr-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500"
                        />
                      </div>
                    </div>
                  </div>

                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-2">
                      Cardholder Name
                    </label>
                    <input
                      type="text"
                      placeholder="John Doe"
                      className="w-full px-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-emerald-500 focus:border-emerald-500"
                    />
                  </div>
                </div>
              )}

              {method === PaymentMethod.WALLET && (
                <div className="text-center py-6">
                  <div className="inline-flex items-center justify-center w-20 h-20 bg-gradient-to-br from-emerald-100 to-green-100 rounded-full mb-4">
                    <Wallet className="w-10 h-10 text-emerald-600" />
                  </div>

                  <div className="mb-6">
                    <p className="text-sm text-gray-600 mb-2">
                      Current Balance
                    </p>
                    <p className="text-4xl font-bold text-gray-900">
                      {user?.wallet_balance?.toLocaleString() || 0}
                      <span className="text-lg text-gray-500 ml-1">THB</span>
                    </p>
                  </div>

                  <div
                    className={`p-4 rounded-xl mb-6 ${
                      (user?.wallet_balance || 0) >= finalPrice
                        ? "bg-emerald-50 border border-emerald-100"
                        : "bg-red-50 border border-red-100"
                    }`}
                  >
                    <div className="flex items-center justify-center mb-2">
                      {(user?.wallet_balance || 0) >= finalPrice ? (
                        <>
                          <CheckCircle className="w-5 h-5 text-emerald-600 mr-2" />
                          <span className="font-medium text-emerald-700">
                            Sufficient Balance
                          </span>
                        </>
                      ) : (
                        <>
                          <AlertCircle className="w-5 h-5 text-red-600 mr-2" />
                          <span className="font-medium text-red-700">
                            Insufficient Balance
                          </span>
                        </>
                      )}
                    </div>
                    <p className="text-sm text-gray-600">
                      Required: {finalPrice} THB | Available:{" "}
                      {user?.wallet_balance || 0} THB
                    </p>
                  </div>

                  {(user?.wallet_balance || 0) < finalPrice && (
                    <button
                      onClick={() => navigate("/wallet/topup")}
                      className="w-full py-3 bg-gray-900 text-white font-medium rounded-lg hover:bg-gray-800 transition-colors mb-4"
                    >
                      Top Up Wallet
                    </button>
                  )}
                </div>
              )}
            </div>

            {/* Error Display */}
            {error && (
              <div className="bg-red-50 border border-red-100 rounded-xl p-4 mb-6 animate-in fade-in slide-in-from-top-2">
                <div className="flex items-center">
                  <AlertCircle className="w-5 h-5 text-red-600 mr-3 flex-shrink-0" />
                  <div>
                    <p className="font-medium text-red-700 mb-1">
                      Payment Error
                    </p>
                    <p className="text-sm text-red-600">{error}</p>
                  </div>
                </div>
              </div>
            )}

            {/* Terms & Conditions */}
            <div className="mb-6">
              <div className="flex items-start">
                <input
                  type="checkbox"
                  id="terms"
                  className="mt-1 mr-3"
                  defaultChecked
                />
                <label htmlFor="terms" className="text-sm text-gray-600">
                  I agree to the Terms of Service and Privacy Policy. I
                  understand that payments are processed securely and refunds
                  are subject to our refund policy.
                </label>
              </div>
            </div>

            {/* Payment Button */}
            <div className="flex flex-col gap-3">
              <button
                onClick={handlePayment}
                disabled={
                  processing ||
                  (method === PaymentMethod.PROMPTPAY && !!qrCodeUrl) ||
                  (method === PaymentMethod.WALLET &&
                    (user?.wallet_balance || 0) < finalPrice)
                }
                className="w-full py-4 bg-gradient-to-r from-emerald-600 to-green-600 text-white font-bold rounded-xl hover:from-emerald-700 hover:to-green-700 transition-all duration-300 shadow-lg shadow-emerald-200 disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center text-lg"
              >
                {processing ? (
                  <>
                    <Loader2 className="w-6 h-6 animate-spin mr-3" />
                    {autotestMode
                      ? "Autotest in progress..."
                      : "Processing Payment..."}
                  </>
                ) : (
                  <>
                    {method === PaymentMethod.PROMPTPAY && qrCodeUrl
                      ? "Waiting for scan..."
                      : `Pay ${finalPrice} THB`}
                    <Shield className="w-5 h-5 ml-3" />
                  </>
                )}
              </button>
              {method === PaymentMethod.PROMPTPAY && (
                <label className="flex items-center gap-2 text-sm text-amber-700 bg-amber-50 border border-amber-200 rounded-lg px-3 py-2">
                  <input
                    type="checkbox"
                    checked={autotestMode}
                    onChange={(e) => {
                      setAutotestMode(e.target.checked);
                      if (e.target.checked) setQrCodeUrl(null);
                    }}
                    className="rounded border-amber-300"
                  />
                  <span>
                    Auto Test (simulate QR scan & verify — no real charge)
                  </span>
                </label>
              )}
            </div>

            <p className="text-center text-sm text-gray-500 mt-4">
              Your payment is secured with 256-bit SSL encryption
            </p>
          </div>

          {/* Support Section */}
          <div className="bg-blue-50 border border-blue-100 rounded-2xl p-6">
            <h4 className="font-bold text-blue-900 mb-2">Need Help?</h4>
            <p className="text-sm text-blue-700 mb-4">
              If you encounter any issues with payment, please contact our
              support team.
            </p>
            <div className="flex gap-3">
              <button
                onClick={() => navigate("/help/payment")}
                className="px-4 py-2 bg-white text-blue-700 font-medium rounded-lg hover:bg-blue-50 transition-colors border border-blue-200"
              >
                Payment FAQ
              </button>
              <button
                onClick={() => navigate("/contact")}
                className="px-4 py-2 bg-blue-600 text-white font-medium rounded-lg hover:bg-blue-700 transition-colors"
              >
                Contact Support
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
