import type { LucideIcon } from "lucide-react";
import {
  Sparkles,
  Wind,
  Droplets,
  Zap,
  Truck,
  Flower2,
  PaintBucket,
  Bug,
  Wrench,
  Sofa,
  Heart,
  ShoppingBag,
  PartyPopper,
  User,
  Briefcase,
  ListOrdered,
  ChefHat,
  Activity,
  Dumbbell,
  PawPrint,
  HandHeart,
  Monitor,
  Code,
  Palette,
  Camera,
  Video,
  Languages,
  Calculator,
  Scale,
  Car,
  Bike,
  GraduationCap,
  CircleDot,
  LayoutGrid,
} from "lucide-react";

/** Category keys must match Jobs.tsx & CreateJob categories + MockApi */
export const JOB_CATEGORY_ICON: Record<string, LucideIcon> = {
  All: LayoutGrid,
  Cleaning: Sparkles,
  AC_Cleaning: Wind,
  Plumbing: Droplets,
  Electrician: Zap,
  Moving: Truck,
  Gardening: Flower2,
  Painting: PaintBucket,
  Pest_Control: Bug,
  Appliance_Repair: Wrench,
  Interior_Design: Sofa,
  Dating: Heart,
  Shopping_Buddy: ShoppingBag,
  Party_Guest: PartyPopper,
  Model: User,
  Consultant: Briefcase,
  Fortune_Telling: Sparkles,
  Queue_Service: ListOrdered,
  Private_Chef: ChefHat,
  Beauty: Sparkles,
  Massage: Heart,
  Physiotherapy: Activity,
  Personal_Trainer: Dumbbell,
  Pet_Care: PawPrint,
  Caregiving: HandHeart,
  IT_Support: Monitor,
  Web_Dev: Code,
  Graphic_Design: Palette,
  Photography: Camera,
  Videography: Video,
  Translation: Languages,
  Accounting: Calculator,
  Legal: Scale,
  Driver: Car,
  Messenger: Bike,
  Tutoring: GraduationCap,
  General: CircleDot,
};

export type JobCategoryGroupId = "home" | "lifestyle" | "health" | "tech" | "logistics";

export const JOB_CATEGORY_GROUPS: { id: JobCategoryGroupId; categories: string[] }[] = [
  {
    id: "home",
    categories: [
      "Cleaning",
      "AC_Cleaning",
      "Plumbing",
      "Electrician",
      "Moving",
      "Gardening",
      "Painting",
      "Pest_Control",
      "Appliance_Repair",
      "Interior_Design",
    ],
  },
  {
    id: "lifestyle",
    categories: [
      "Dating",
      "Shopping_Buddy",
      "Party_Guest",
      "Model",
      "Consultant",
      "Fortune_Telling",
      "Queue_Service",
      "Private_Chef",
    ],
  },
  {
    id: "health",
    categories: ["Beauty", "Massage", "Physiotherapy", "Personal_Trainer", "Pet_Care", "Caregiving"],
  },
  {
    id: "tech",
    categories: [
      "IT_Support",
      "Web_Dev",
      "Graphic_Design",
      "Photography",
      "Videography",
      "Translation",
      "Accounting",
      "Legal",
    ],
  },
  {
    id: "logistics",
    categories: ["Driver", "Messenger", "Tutoring", "General"],
  },
];

export const GROUP_ACCENT: Record<
  JobCategoryGroupId,
  { bar: string; tile: string; iconWrap: string }
> = {
  home: {
    bar: "from-emerald-500/90 to-teal-600/80",
    tile: "border-emerald-200/90 bg-gradient-to-br from-emerald-50 to-white hover:border-emerald-400/60",
    iconWrap: "bg-emerald-100 text-emerald-800",
  },
  lifestyle: {
    bar: "from-violet-500/85 to-fuchsia-600/75",
    tile: "border-violet-200/90 bg-gradient-to-br from-violet-50 to-white hover:border-violet-400/60",
    iconWrap: "bg-violet-100 text-violet-800",
  },
  health: {
    bar: "from-rose-500/85 to-pink-600/75",
    tile: "border-rose-200/90 bg-gradient-to-br from-rose-50 to-white hover:border-rose-400/60",
    iconWrap: "bg-rose-100 text-rose-800",
  },
  tech: {
    bar: "from-sky-500/85 to-blue-600/75",
    tile: "border-sky-200/90 bg-gradient-to-br from-sky-50 to-white hover:border-sky-400/60",
    iconWrap: "bg-sky-100 text-sky-800",
  },
  logistics: {
    bar: "from-amber-500/85 to-orange-600/75",
    tile: "border-amber-200/90 bg-gradient-to-br from-amber-50 to-white hover:border-amber-400/60",
    iconWrap: "bg-amber-100 text-amber-900",
  },
};
