export const BUILTIN_WORKFLOW_TEMPLATES = Object.freeze([
  {
    id: 'wf-resume',
    name: 'Resume Workflow',
    version: '1.0.0',
    description: 'Standard resume generation workflow',
    skill: 'ai-resume',
    category: 'resume',
    pipelineTemplate: 'videoPipelineV1',
    requiredCapabilities: ['resume_generation', 'text_generation'],
    requiredKnowledge: ['resume'],
    requiredPolicies: ['writing'],
    requiredMarketplacePackages: ['resume-ai'],
    variables: [{ name: 'role', scope: 'input', required: true }, { name: 'goals', scope: 'input', required: true }],
    outputs: ['resume_pdf', 'profile_summary'],
  },
  {
    id: 'wf-marketplace',
    name: 'Marketplace Workflow',
    version: '1.0.0',
    description: 'Marketplace listing generation workflow',
    skill: 'ai-marketplace',
    category: 'marketplace',
    pipelineTemplate: 'videoPipelineV1',
    requiredCapabilities: ['marketplace_generation'],
    requiredKnowledge: ['catalog'],
    requiredPolicies: ['writing'],
    requiredMarketplacePackages: ['resume-ai'],
    variables: [{ name: 'listingTitle', scope: 'input' }],
    outputs: ['listing_draft'],
  },
  {
    id: 'wf-restaurant',
    name: 'Restaurant Workflow',
    version: '1.0.0',
    description: 'Restaurant menu and operations workflow',
    skill: 'ai-restaurant',
    category: 'restaurant',
    pipelineTemplate: 'videoPipelineV1',
    requiredCapabilities: ['food_generation'],
    requiredKnowledge: [],
    requiredPolicies: ['writing'],
    requiredMarketplacePackages: [],
    variables: [{ name: 'cuisine', scope: 'input' }],
    outputs: ['menu'],
  },
  {
    id: 'wf-food-delivery',
    name: 'Food Delivery Workflow',
    version: '1.0.0',
    description: 'Food delivery catalog workflow',
    skill: 'ai-food',
    category: 'food_delivery',
    pipelineTemplate: 'videoPipelineV1',
    requiredCapabilities: ['food_generation'],
    requiredKnowledge: [],
    requiredPolicies: ['writing'],
    requiredMarketplacePackages: [],
    variables: [{ name: 'deliveryZone', scope: 'input' }],
    outputs: ['delivery_menu'],
  },
  {
    id: 'wf-hotel-booking',
    name: 'Hotel Booking Workflow',
    version: '1.0.0',
    description: 'Hotel search and booking content workflow',
    skill: 'ai-hotel',
    category: 'hotel',
    pipelineTemplate: 'videoPipelineV1',
    requiredCapabilities: ['hotel_generation'],
    requiredKnowledge: [],
    requiredPolicies: ['writing'],
    requiredMarketplacePackages: [],
    variables: [{ name: 'city', scope: 'input' }],
    outputs: ['hotel_listing'],
  },
  {
    id: 'wf-trip-planner',
    name: 'Trip Planner Workflow',
    version: '1.0.0',
    description: 'Travel itinerary planning workflow',
    skill: 'ai-trip',
    category: 'trip',
    pipelineTemplate: 'videoPipelineV1',
    requiredCapabilities: ['travel_generation'],
    requiredKnowledge: [],
    requiredPolicies: ['writing'],
    requiredMarketplacePackages: [],
    variables: [{ name: 'destination', scope: 'input' }],
    outputs: ['itinerary'],
  },
  {
    id: 'wf-insurance',
    name: 'Insurance Workflow',
    version: '1.0.0',
    description: 'Insurance policy analysis workflow',
    skill: 'ai-insurance',
    category: 'insurance',
    pipelineTemplate: 'videoPipelineV1',
    requiredCapabilities: ['insurance_generation'],
    requiredKnowledge: [],
    requiredPolicies: ['structured_json'],
    requiredMarketplacePackages: [],
    variables: [{ name: 'coverageType', scope: 'input' }],
    outputs: ['policy_summary'],
  },
  {
    id: 'wf-lead-generation',
    name: 'Lead Generation Workflow',
    version: '1.0.0',
    description: 'Lead capture and nurture workflow',
    skill: 'ai-marketplace',
    category: 'lead_generation',
    pipelineTemplate: 'videoPipelineV1',
    requiredCapabilities: ['text_generation', 'marketplace_generation'],
    requiredKnowledge: [],
    requiredPolicies: ['writing'],
    requiredMarketplacePackages: [],
    variables: [{ name: 'leadSource', scope: 'input' }],
    outputs: ['lead_pack'],
  },
  {
    id: 'wf-video-marketing',
    name: 'Video Marketing Workflow',
    version: '1.0.0',
    description: 'Video marketing campaign workflow',
    skill: 'ai-resume',
    category: 'video_marketing',
    pipelineTemplate: 'videoPipelineV1',
    requiredCapabilities: ['video_generation', 'text_generation'],
    requiredKnowledge: [],
    requiredPolicies: ['writing'],
    requiredMarketplacePackages: ['resume-ai'],
    variables: [{ name: 'campaignName', scope: 'input' }],
    outputs: ['video_brief', 'publish_package'],
  },
  {
    id: 'wf-commerce',
    name: 'Commerce Workflow',
    version: '1.0.0',
    description: 'General commerce workflow',
    skill: 'ai-marketplace',
    category: 'commerce',
    pipelineTemplate: 'videoPipelineV1',
    requiredCapabilities: ['marketplace_generation'],
    requiredKnowledge: ['catalog'],
    requiredPolicies: ['writing'],
    requiredMarketplacePackages: [],
    variables: [{ name: 'productName', scope: 'input' }],
    outputs: ['commerce_listing'],
  },
]);

export function getWorkflowTemplate(id) {
  return BUILTIN_WORKFLOW_TEMPLATES.find((t) => t.id === id) || null;
}
