export const VERTICAL_SKILL_TEMPLATES = Object.freeze([
  {
    id: 'ai-resume',
    name: 'AI Resume',
    version: '1.0.0',
    description: 'Vertical skill for AI-powered resume generation and profile analysis',
    capabilities: ['resume_generation', 'text_generation'],
    permissions: ['runtime.jobs.submit', 'governance.audit'],
    requiredPlugins: ['resume-ai'],
    requiredPipelines: ['video-pipeline-v1'],
    requiredModels: ['hermes3:3b'],
    requiredPolicies: ['writing'],
    requiredMarketplacePackages: ['resume-ai'],
  },
  {
    id: 'ai-marketplace',
    name: 'AI Marketplace',
    version: '1.0.0',
    description: 'Vertical skill for marketplace listing and catalog generation',
    capabilities: ['marketplace_generation', 'text_generation'],
    permissions: ['runtime.jobs.submit', 'billing.meter'],
    requiredPlugins: ['resume-ai'],
    requiredPipelines: ['default'],
    requiredModels: ['hermes3:3b'],
    requiredPolicies: ['writing'],
    requiredMarketplacePackages: ['resume-ai'],
  },
  {
    id: 'ai-food',
    name: 'AI Food',
    version: '1.0.0',
    description: 'Vertical skill for menu and recipe generation',
    capabilities: ['food_generation', 'text_generation'],
    permissions: ['runtime.jobs.submit'],
    requiredPlugins: [],
    requiredPipelines: ['default'],
    requiredModels: ['hermes3:3b'],
    requiredPolicies: ['writing'],
    requiredMarketplacePackages: [],
  },
  {
    id: 'ai-hotel',
    name: 'AI Hotel',
    version: '1.0.0',
    description: 'Vertical skill for hotel search and booking content',
    capabilities: ['hotel_generation', 'text_generation'],
    permissions: ['runtime.jobs.submit'],
    requiredPlugins: [],
    requiredPipelines: ['default'],
    requiredModels: ['hermes3:3b'],
    requiredPolicies: ['writing'],
    requiredMarketplacePackages: [],
  },
  {
    id: 'ai-trip',
    name: 'AI Trip',
    version: '1.0.0',
    description: 'Vertical skill for travel itinerary generation',
    capabilities: ['travel_generation', 'text_generation'],
    permissions: ['runtime.jobs.submit'],
    requiredPlugins: [],
    requiredPipelines: ['default'],
    requiredModels: ['hermes3:3b'],
    requiredPolicies: ['writing'],
    requiredMarketplacePackages: [],
  },
  {
    id: 'ai-insurance',
    name: 'AI Insurance',
    version: '1.0.0',
    description: 'Vertical skill for insurance policy and coverage analysis',
    capabilities: ['insurance_generation', 'text_generation'],
    permissions: ['runtime.jobs.submit', 'governance.audit'],
    requiredPlugins: [],
    requiredPipelines: ['default'],
    requiredModels: ['hermes3:3b'],
    requiredPolicies: ['structured_json'],
    requiredMarketplacePackages: [],
  },
  {
    id: 'ai-restaurant',
    name: 'AI Restaurant',
    version: '1.0.0',
    description: 'Vertical skill for restaurant menu and operations content',
    capabilities: ['food_generation', 'text_generation'],
    permissions: ['runtime.jobs.submit'],
    requiredPlugins: [],
    requiredPipelines: ['default'],
    requiredModels: ['hermes3:3b'],
    requiredPolicies: ['writing'],
    requiredMarketplacePackages: [],
  },
]);

export function getSkillTemplate(id) {
  return VERTICAL_SKILL_TEMPLATES.find((t) => t.id === id) || null;
}

export function listSkillTemplates() {
  return VERTICAL_SKILL_TEMPLATES.map((t) => ({ ...t }));
}
